"""VPype Processor plugin."""

from __future__ import annotations

import asyncio
import math
import shutil
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from app.plugin_base import (
    BasePlugin,
    ParameterDefinition,
    PluginSchema,
    PortDefinition,
    PortType,
)

_PAGE_SIZES = {"a6", "a5", "a4", "a3", "a2", "a1", "a0", "letter", "legal", "tabloid"}


def _coerce_float(
    params: dict[str, Any],
    key: str,
    default: float,
    *,
    minimum: float | None = None,
    maximum: float | None = None,
) -> float:
    try:
        value = float(params.get(key, default))
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Parameter '{key}' must be a number") from exc
    if not math.isfinite(value):
        raise ValueError(f"Parameter '{key}' must be finite")
    if minimum is not None and value < minimum:
        raise ValueError(f"Parameter '{key}' must be >= {minimum}")
    if maximum is not None and value > maximum:
        raise ValueError(f"Parameter '{key}' must be <= {maximum}")
    return value


def _coerce_bool(params: dict[str, Any], key: str, default: bool) -> bool:
    return bool(params.get(key, default))


def _format_mm(value: float) -> str:
    return f"{value:.6f}mm"


class VPypeProcessor(BasePlugin):
    @classmethod
    def schema(cls) -> PluginSchema:
        return PluginSchema(
            name="VPype Processor",
            category="Processing",
            description="file:details.md",
            inputs=[
                PortDefinition(
                    name="vector",
                    type=PortType.VECTOR,
                    description="Input SVG document as XML text.",
                ),
            ],
            outputs=[
                PortDefinition(
                    name="vector",
                    type=PortType.VECTOR,
                    description="Processed SVG document generated by vpype.",
                ),
            ],
            parameters=[
                ParameterDefinition(
                    name="enable_linemerge",
                    type="boolean",
                    default=True,
                    description="Merge connected lines within a tolerance.",
                ),
                ParameterDefinition(
                    name="linemerge_tolerance_mm",
                    type="number",
                    default=0.1,
                    min=0.0,
                    max=10.0,
                    step=0.01,
                    visible_if={"parameter": "enable_linemerge", "equals": True},
                    description="Maximum endpoint distance for line merging (mm).",
                ),
                ParameterDefinition(
                    name="enable_linesort",
                    type="boolean",
                    default=True,
                    description="Sort paths to reduce pen-up travel distance.",
                ),
                ParameterDefinition(
                    name="enable_reloop",
                    type="boolean",
                    default=False,
                    description="Randomize closed-path seam location.",
                ),
                ParameterDefinition(
                    name="reloop_tolerance_mm",
                    type="number",
                    default=0.05,
                    min=0.0,
                    max=10.0,
                    step=0.01,
                    visible_if={"parameter": "enable_reloop", "equals": True},
                    description="Tolerance used to detect closed paths for reloop (mm).",
                ),
                ParameterDefinition(
                    name="enable_linesimplify",
                    type="boolean",
                    default=False,
                    description="Simplify paths by reducing point count.",
                ),
                ParameterDefinition(
                    name="linesimplify_tolerance_mm",
                    type="number",
                    default=0.05,
                    min=0.0,
                    max=10.0,
                    step=0.01,
                    visible_if={"parameter": "enable_linesimplify", "equals": True},
                    description="Maximum simplification deviation from source geometry (mm).",
                ),
                ParameterDefinition(
                    name="min_path_length_mm",
                    type="number",
                    default=0.0,
                    min=0.0,
                    max=100000.0,
                    step=0.1,
                    description="Drop paths shorter than this threshold (mm). 0 disables filtering.",
                ),
                ParameterDefinition(
                    name="translate_x_mm",
                    type="number",
                    default=0.0,
                    min=-100000.0,
                    max=100000.0,
                    step=0.1,
                    description="Horizontal translation offset (mm).",
                ),
                ParameterDefinition(
                    name="translate_y_mm",
                    type="number",
                    default=0.0,
                    min=-100000.0,
                    max=100000.0,
                    step=0.1,
                    description="Vertical translation offset (mm).",
                ),
                ParameterDefinition(
                    name="scale_factor",
                    type="number",
                    default=1.0,
                    min=0.001,
                    max=1000.0,
                    step=0.01,
                    description="Uniform geometry scale factor.",
                ),
                ParameterDefinition(
                    name="rotate_deg",
                    type="number",
                    default=0.0,
                    min=-3600.0,
                    max=3600.0,
                    step=0.1,
                    description="Clockwise rotation angle in degrees.",
                ),
                ParameterDefinition(
                    name="layout_mode",
                    type="select",
                    default="none",
                    options=["none", "page", "fit_to_margins", "tight"],
                    description="Optional vpype layout mode.",
                ),
                ParameterDefinition(
                    name="page_size",
                    type="select",
                    default="a4",
                    options=sorted(_PAGE_SIZES),
                    visible_if={"parameter": "layout_mode", "one_of": ["page", "fit_to_margins"]},
                    description="Target page size for layout modes using fixed pages.",
                ),
                ParameterDefinition(
                    name="layout_margin_mm",
                    type="number",
                    default=10.0,
                    min=0.0,
                    max=1000.0,
                    step=0.1,
                    visible_if={"parameter": "layout_mode", "equals": "fit_to_margins"},
                    description="Margin used by fit_to_margins mode (mm).",
                ),
                ParameterDefinition(
                    name="timeout_seconds",
                    type="number",
                    default=20,
                    min=1,
                    max=300,
                    step=1,
                    description="Maximum vpype execution time before aborting.",
                ),
            ],
        )

    async def process(self, inputs: dict[str, Any], params: dict[str, Any]) -> dict[str, Any]:
        svg = (inputs or {}).get("vector")
        if not isinstance(svg, str) or not svg.strip():
            raise ValueError("Input 'vector' must be a non-empty SVG string")

        binary = shutil.which("vpype")
        if binary is None:
            raise RuntimeError("vpype executable not found in PATH")

        timeout_seconds = _coerce_float(params, "timeout_seconds", 20, minimum=1, maximum=300)

        with tempfile.TemporaryDirectory(prefix="vpype_processor_") as tmp_dir:
            tmp_path = Path(tmp_dir)
            input_path = tmp_path / "input.svg"
            output_path = tmp_path / "output.svg"
            input_path.write_text(svg, encoding="utf-8")

            full_cmd = self._build_command(binary, input_path, output_path, params)

            process = await asyncio.create_subprocess_exec(
                *full_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )

            try:
                stdout, stderr = await asyncio.wait_for(
                    process.communicate(),
                    timeout=timeout_seconds,
                )
            except asyncio.TimeoutError:
                process.kill()
                await process.communicate()
                raise RuntimeError(f"vpype timed out after {int(timeout_seconds)}s")

            if process.returncode != 0:
                stderr_text = stderr.decode("utf-8", errors="replace").strip()
                stdout_text = stdout.decode("utf-8", errors="replace").strip()
                details = stderr_text or stdout_text or "no diagnostics available"
                raise RuntimeError(f"vpype failed: {details}")

            if not output_path.is_file():
                raise RuntimeError("vpype did not produce output SVG")

            out_svg = output_path.read_text(encoding="utf-8")
            try:
                root = ET.fromstring(out_svg)
            except ET.ParseError as exc:
                raise RuntimeError(f"vpype produced invalid XML output: {exc}") from exc
            if not root.tag.lower().endswith("svg"):
                raise RuntimeError("vpype output root element is not <svg>")
            return {"vector": out_svg}

    @staticmethod
    def _build_command(
        binary: str,
        input_path: Path,
        output_path: Path,
        params: dict[str, Any],
    ) -> list[str]:
        command: list[str] = [binary, "read", str(input_path)]

        enable_linemerge = _coerce_bool(params, "enable_linemerge", True)
        if enable_linemerge:
            tol = _coerce_float(
                params,
                "linemerge_tolerance_mm",
                0.1,
                minimum=0.0,
                maximum=10.0,
            )
            command.extend(["linemerge", "--tolerance", _format_mm(tol)])

        if _coerce_bool(params, "enable_linesort", True):
            command.append("linesort")

        if _coerce_bool(params, "enable_reloop", False):
            tol = _coerce_float(
                params,
                "reloop_tolerance_mm",
                0.05,
                minimum=0.0,
                maximum=10.0,
            )
            command.extend(["reloop", "--tolerance", _format_mm(tol)])

        if _coerce_bool(params, "enable_linesimplify", False):
            tol = _coerce_float(
                params,
                "linesimplify_tolerance_mm",
                0.05,
                minimum=0.0,
                maximum=10.0,
            )
            command.extend(["linesimplify", "--tolerance", _format_mm(tol)])

        min_length = _coerce_float(
            params,
            "min_path_length_mm",
            0.0,
            minimum=0.0,
            maximum=100000.0,
        )
        if min_length > 0:
            command.extend(["filter", "--min-length", _format_mm(min_length)])

        tx = _coerce_float(params, "translate_x_mm", 0.0, minimum=-100000.0, maximum=100000.0)
        ty = _coerce_float(params, "translate_y_mm", 0.0, minimum=-100000.0, maximum=100000.0)
        if abs(tx) > 1e-9 or abs(ty) > 1e-9:
            command.extend(["translate", "--", _format_mm(tx), _format_mm(ty)])

        scale = _coerce_float(params, "scale_factor", 1.0, minimum=0.001, maximum=1000.0)
        if abs(scale - 1.0) > 1e-9:
            command.extend(["scale", f"{scale:.6f}"])

        rotate = _coerce_float(params, "rotate_deg", 0.0, minimum=-3600.0, maximum=3600.0)
        if abs(rotate) > 1e-9:
            command.extend(["rotate", "--", f"{rotate:.6f}deg"])

        layout_mode = str(params.get("layout_mode", "none"))
        if layout_mode not in {"none", "page", "fit_to_margins", "tight"}:
            raise ValueError("Parameter 'layout_mode' has an unsupported value")

        if layout_mode in {"page", "fit_to_margins"}:
            page_size = str(params.get("page_size", "a4")).lower().strip()
            if page_size not in _PAGE_SIZES:
                raise ValueError("Parameter 'page_size' has an unsupported value")
            if layout_mode == "fit_to_margins":
                margin = _coerce_float(
                    params,
                    "layout_margin_mm",
                    10.0,
                    minimum=0.0,
                    maximum=1000.0,
                )
                command.extend(["layout", "--fit-to-margins", _format_mm(margin), page_size])
            else:
                command.extend(["layout", page_size])
        elif layout_mode == "tight":
            command.extend(["layout", "tight"])

        command.extend(["write", str(output_path)])
        return command


Plugin = VPypeProcessor
